# Generated by Django 4.1.3 on 2022-11-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('short_url', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('long_url', models.CharField(max_length=65535)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(max_length=65535, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_urls_app.link')),
            ],
        ),
    ]
