# Generated by Django 4.2 on 2023-07-11 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('short_urls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['short_url'], 'verbose_name': 'Short URLs', 'verbose_name_plural': 'Short URLs'},
        ),
        migrations.AddField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='link',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Выключенные ссылки не обрабатываются', verbose_name='Включить ссылку'),
        ),
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.CharField(max_length=65535, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False, verbose_name='Короткая ссылка'),
        ),
    ]
